#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client'
cookbook 'mongodb'
cookbook 'build-essential'
cookbook 'git'
cookbook 'zsh'

cookbook 'ruby-build',
  git: 'git://github.com/arkency/ruby-build-cookbook.git'

cookbook 'ruby',
  git: 'git://github.com/leifg/marozi-cookbooks'

cookbook 'bootstrap',
  git: 'git://github.com/leifg/cookbooks'


# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
